# Generated by Django 2.0 on 2018-12-13 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(default='K100', max_length=210, verbose_name='车票编号')),
                ('name_start', models.CharField(default='', max_length=30, verbose_name='始发站')),
                ('name_end', models.CharField(default='', max_length=30, verbose_name='终点站')),
                ('date', models.CharField(max_length=50, verbose_name='车票日期')),
                ('time', models.CharField(max_length=50, verbose_name='车票发车时间')),
                ('brief', models.TextField(max_length=300, null=True, verbose_name='车票信息')),
                ('seats', models.IntegerField(default=45, verbose_name='剩余座位')),
            ],
            options={
                'verbose_name': '车票信息',
                'verbose_name_plural': '车票信息',
                'db_table': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='用户手机号')),
                ('password', models.CharField(default='', max_length=20, verbose_name='账户密码')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='用户姓名')),
                ('createTime', models.DateField(verbose_name='账户创建时间')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='账户关联邮箱')),
                ('ticket_num', models.CharField(max_length=10, null=True, verbose_name='购买车票编号')),
                ('ticket_name', models.CharField(max_length=30, null=True, verbose_name='购买车票名称')),
                ('ticket_seat_num', models.IntegerField(null=True, verbose_name='购买车票座位号')),
                ('ticket_time', models.CharField(max_length=50, null=True, verbose_name='购买车票发车时间')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'Users',
            },
        ),
    ]
